// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8vpda7rsYPZ3X6J0u-m8PlBeeTRG2u0',
    appId: '1:398699819766:android:69bc11a6f305d452c9f2d7',
    messagingSenderId: '398699819766',
    projectId: 'notesq',
    storageBucket: 'notesq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkpXwu6F9IVZ3nNAAPsylSPN5LUPgzjM',
    appId: '1:398699819766:ios:cb1843b650c90ed7c9f2d7',
    messagingSenderId: '398699819766',
    projectId: 'notesq',
    storageBucket: 'notesq.appspot.com',
    iosClientId: '398699819766-3ijem300pqhln7nnfogcv6rjvrj9punf.apps.googleusercontent.com',
    iosBundleId: 'com.peacelabs.notesq',
  );
}
